### ISSUE TITLE
Cannot run the app

### ISSUE THREAD

**Issue by daixtrose** [ericmdantas/ng2-chat#5]
Maybe this code is not ready or I am missing something:

``` cmd
\ng2-chat>npm start

> ng2-chat@1.0.0 start C:\Users\numer\Documents\PROJECT\ng2-chat
> nodemon --watch common.js --watch server.js --watch server --exec babel-node server.js

[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: common.js server.js C:\Users\numer\Documents\PROJECT\ng2-chat\server/**/*
[nodemon] starting `babel-node server.js`
listening on port: 9999
```

Output of browser debug session on http://localhost:9999 which shows a picture from IBM:

![image](https://cloud.githubusercontent.com/assets/5588692/16567339/dd6de9ba-421d-11e6-865b-2c3b07e8623d.png)

```
GET http://localhost:9999/config.js 
localhost/:17 GET http://localhost:9999/config.js 
zone.js:101 GET http://localhost:9999/client.js 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM314:3Z @ system.src.js:5123(anonymous function) @ system.src.js:5123ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474
zone.js:101 XHR finished loading: GET "http://localhost:9999/client.js".scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM314:3Z @ system.src.js:5123(anonymous function) @ system.src.js:5123ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123(anonymous function) @ system.src.js:5123ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474
zone.js:461 Unhandled Promise rejection: (SystemJS) Error: XHR error (404 Not Found) loading http://localhost:9999/client.js
        at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9999/node_modules/zone.js/dist/zone.js:769:30)
        at ZoneDelegate.invokeTask (http://localhost:9999/node_modules/zone.js/dist/zone.js:356:38)
        at Zone.runTask (http://localhost:9999/node_modules/zone.js/dist/zone.js:256:48)
        at XMLHttpRequest.ZoneTask.invoke (http://localhost:9999/node_modules/zone.js/dist/zone.js:423:34)
    Error loading http://localhost:9999/client.js ; Zone: <root> ; Task: Promise.then ; Value: Error: (SystemJS) Error: XHR error (404 Not Found) loading http://localhost:9999/client.js(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Error: (SystemJS) Error: XHR error (404 Not Found) loading http://localhost:9999/client.js(…)
```

**Comment by ericmdantas** [comment]
Run `tsc` and refresh the page.

**Comment by daixtrose** [comment]
Am I in the wrong directory?

``` cmd
ng2-chat>tsc
app/chat/chat_cmp.ts(6,27): error TS2307: Cannot find module 'app/chat/chat_list/chat_list_cmp'.
app/chat/chat_cmp.ts(7,27): error TS2307: Cannot find module 'app/chat/chat_form/chat_form_cmp'.
app/chat/chat_cmp.ts(8,29): error TS2307: Cannot find module 'app/chat/chat_list/chat_list_model'.
app/chat/services/chat_service.ts(6,28): error TS2307: Cannot find module 'app/chat/message/message_model'.
app/chat/services/chat_service.ts(12,12): error TS2304: Cannot find name 'SocketIOStatic'.
app/chat/services/chat_service.ts(12,29): error TS2304: Cannot find name 'io'.
node_modules/@angular/core/src/application_ref.d.ts(79,88): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(137,42): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(196,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(115,123): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(115,165): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/async.d.ts(34,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/async.d.ts(35,45): error TS2304: Cannot find name 'Promise'.
[60 lines missing]
app/chat/chat_form/chat_form_cmp.ts(19,30): error TS2307: Cannot find module 'app/chat/chat_list/mention_service'.
app/chat/chat_form/chat_form_cmp.ts(20,35): error TS2307: Cannot find module 'app/chat/chat_form/user_typing_directive'.
app/chat/chat_form/chat_form_cmp.ts(21,29): error TS2307: Cannot find module 'app/chat/chat_list/chat_list_model'.
app/chat/chat_form/chat_form_cmp.ts(22,32): error TS2307: Cannot find module 'app/chat/chat_promptify/promptify_service'.
app/chat/chat_form/chat_form_cmp.ts(23,31): error TS2307: Cannot find module 'app/chat/chat_form/arrows_directive'.
app/chat/chat_form/chat_form_cmp.ts(24,37): error TS2307: Cannot find module 'app/chat/message/message_storage_service'.
app/chat/chat_form/chat_form_cmp.ts(103,33): error TS2339: Property 'FormControls' does not exist on type 'FormGroup'.
app/chat/chat_form/chat_form_cmp.ts(108,49): error TS2339: Property 'FormControls' does not exist on type 'FormGroup'.
app/chat/chat_form/chat_form_cmp.ts(111,33): error TS2339: Property 'FormControls' does not exist on type 'FormGroup'.
[15 lines missing]
app/chat/chat_list/chat_user_online_message_service.ts(1,34): error TS2307: Cannot find module 'app/user/user_storage_service'.
app/chat/chat_list/chat_user_online_message_service.ts(2,28): error TS2307: Cannot find module 'app/chat/message/message_model'.
app/chat/chat_list/chat_user_online_message_service.ts(3,27): error TS2307: Cannot find module 'app/chat/services/chat_service'.
app/chat/chat_list/chat_user_online_message_service.ts(4,27): error TS2307: Cannot find module 'app/chat/chat_list/chat_list_cmp'.
app/chat/chat_list/mention_service.ts(1,28): error TS2307: Cannot find module 'app/chat/message/message_model'.
app/chat/chat_list/mention_service.ts(2,34): error TS2307: Cannot find module 'app/user/user_storage_service'.
[35 lines mssing]
app/roll/roll.ts(12,20): error TS2304: Cannot find name 'SocketIOStatic'.
app/roll/roll.ts(12,37): error TS2304: Cannot find name 'io'.
app/user/user_storage_service.ts(1,23): error TS2307: Cannot find module 'xtorage'.
app/user/user_storage_service.ts(2,25): error TS2307: Cannot find module 'app/user/user_model'.
client.ts(3,22): error TS2307: Cannot find module 'app/app_cmp'.
config.ts(1,1): error TS2304: Cannot find name 'System'.
```

**Comment by daixtrose** [comment]
Ooops! I forgot ``npm install`, sorry! Now I see 

![image](https://cloud.githubusercontent.com/assets/5588692/16591176/f006d9ac-42da-11e6-957a-31d0753e1846.png)

Is that what you expect? Where is this terminal running?

**Comment by ericmdantas** [comment]
Yup, thats the expected behavior. I didnt care much about the typings, because I only created this for fun.

As for the terminal, what terminal? The fake one in the page is the "form" where you send and receive messages.

**Comment by ericmdantas** [comment]
Did you get a login modal to enter a username?

**Comment by daixtrose** [comment]
Yes, I did

**Comment by ericmdantas** [comment]
Well, it's working then :smile:

**Comment by daixtrose** [comment]
I was surprised to see some kind of VM with a terminal window. What system are you using here?

**Comment by daixtrose** [comment]
And back to the original problem: I simple forgot the required

> npm install

**Comment by ericmdantas** [comment]
Heh, I did the whole layout for fun, to trick people into thinking that was a desktop app.
